# Generated by Django 5.1.5 on 2025-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
