# Generated by Django 5.1.5 on 2025-02-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_remove_rental_bike_bike_bikecategory_rental_bike_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='bike_num',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
