# Generated by Django 5.1.5 on 2025-02-21 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_rentbike_bikebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, default='default_product', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.products'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.products'),
            preserve_default=False,
        ),
    ]
