# Generated by Django 5.1.5 on 2025-02-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikebooking',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.rentbike'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecomapp.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.products'),
        ),
    ]
