# Generated by Django 5.1.5 on 2025-02-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0029_remove_products_rating_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='rating',
        ),
    ]
